services:
  ur-service:
    build:
      context: ./url-shortener-service
    container_name: backend
    ports:
      - "3000:3000"
    depends_on: 
      - redis
    volumes:
      - ./url-shortener-service:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run start:dev"

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - rabbitmq
    environment:
      REDIS_HOST: redis

  kong:
    image: kong:3.6
    platform: linux/amd64
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yaml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./kong:/kong
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - backend # âœ… FIXED

  sonarqube:
    image: sonarqube:lts
    platform: linux/amd64
    ports:
      - "9000:9000"

  graphql-service:
    build: ./graphql-service
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - url-service
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
