apiVersion: apps/v1
kind: Deployment
metadata:
  name: ur-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ur-service
  template:
    metadata:
      labels:
        app: ur-service
    spec:
      containers:
        - name: ur-service
          image: url-shortener-service
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: redis
---
apiVersion: v1
kind: Service
metadata:
  name: ur-service
spec:
  selector:
    app: ur-service
  ports:
    - port: 3000
      targetPort: 3000